using System.Text;

namespace IQOne.Zero.Regify.Mapping;

/// <summary>Emits Entity Framework configurations. A second ORM needs a sibling emitter.</summary>
internal static class EfMappingEmitter
{
    public const string ProviderName = "Ef";

    public static string Emit(string @namespace, EntitySchema entity, string entityFullName)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        builder.AppendLine();
        builder.AppendLine($"namespace {@namespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Generated from the schema definition. Express relationships,");
        builder.AppendLine("/// owned types and converters in a partial of this class.</summary>");
        builder.AppendLine($"public sealed partial class {entity.EntityName}Map");
        builder.AppendLine($"    : global::Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<{entityFullName}>");
        builder.AppendLine("{");
        builder.AppendLine("    public void Configure(");
        builder.AppendLine($"        global::Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{entityFullName}> builder)");
        builder.AppendLine("    {");

        var schema = entity.Schema is null ? "null" : $"\"{entity.Schema}\"";
        builder.AppendLine($"        builder.ToTable(\"{entity.Table}\", {schema});");
        builder.AppendLine();
        builder.AppendLine($"        builder.HasKey(e => e.{entity.Key});");
        builder.AppendLine($"        builder.Property(e => e.{entity.Key}).HasColumnName(\"{entity.Key}\").ValueGeneratedOnAdd();");
        builder.AppendLine();

        foreach (var column in entity.Columns)
        {
            builder.Append($"        builder.Property(e => e.{column.Property}).HasColumnName(\"{column.Column}\")");

            if (column.MaxLength is { } length) builder.Append($".HasMaxLength({length})");
            if (column.ColumnType is { } type) builder.Append($".HasColumnType(\"{type}\")");
            if (column.Required) builder.Append(".IsRequired()");

            builder.AppendLine(";");
        }

        if (entity.Legacy)
        {
            builder.AppendLine();
            builder.AppendLine("        // Shared row contract. The concurrency token is applied by LegacyDbContext.");

            foreach (var legacy in new[]
                     { "RecordStamp", "State", "CreatedByLoginId", "CreatedDate", "ModifiedByLoginId", "ModifiedDate" })
                builder.AppendLine($"        builder.Property(e => e.{legacy}).HasColumnName(\"{legacy}\");");
        }

        builder.AppendLine();
        builder.AppendLine("        OnConfiguring(builder);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Hook for configuration the schema cannot express.</summary>");
        builder.AppendLine("    partial void OnConfiguring(");
        builder.AppendLine($"        global::Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<{entityFullName}> builder);");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
