using System.Collections.Immutable;
using System.Text;
using IQOne.Zero.Regify.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IQOne.Zero.Regify.Mapping;

/// <summary>
/// Generates entity mappings from <c>*.schema.json</c> files.
/// </summary>
/// <remarks>
/// The schema describes provider-neutral facts. The emitter is selected by
/// <c>RegifyDataProvider</c> and its name is embedded in the generated output, so the
/// compile-time and runtime providers cannot diverge.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class MappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue(PlatformNames.ProviderProperty, out var name)
             && !string.IsNullOrWhiteSpace(name)
                ? name
                : EfMappingEmitter.ProviderName);

        var schemas = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".schema.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, token) => new SchemaFile(
                Path: file.Path,
                Content: file.GetText(token)?.ToString() ?? string.Empty))
            .Collect();

        var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) ? ns : "Generated");

        context.RegisterSourceOutput(
            schemas.Combine(provider).Combine(rootNamespace).Combine(context.CompilationProvider),
            static (spc, input) => Emit(
                spc,
                input.Left.Left.Left,
                input.Left.Left.Right,
                input.Left.Right,
                input.Right));
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<SchemaFile> files,
        string providerName,
        string rootNamespace,
        Compilation compilation)
    {
        if (files.IsDefaultOrEmpty) return;

        if (!string.Equals(providerName, EfMappingEmitter.ProviderName, StringComparison.OrdinalIgnoreCase))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MappingDiagnostics.UnknownProvider, Location.None, providerName));
            return;
        }

        var tables = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in files)
        {
            var root = Json.Parse(file.Content);

            if (root is null || !root.IsObject)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MappingDiagnostics.SchemaUnreadable, Location.None, Path(file.Path)));
                continue;
            }

            foreach (var pair in root.Object)
            {
                var entity = Read(pair.Key, pair.Value);

                if (entity is null) continue;

                var symbol = FindEntity(compilation, entity.EntityName);

                if (symbol is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        MappingDiagnostics.EntityNotFound, Location.None, entity.EntityName));
                    continue;
                }

                if (!Validate(context, entity, symbol)) continue;

                var tableKey = $"{entity.Schema}.{entity.Table}";

                if (tables.TryGetValue(tableKey, out var owner))
                    context.ReportDiagnostic(Diagnostic.Create(
                        MappingDiagnostics.DuplicateTable, Location.None, tableKey, owner, entity.EntityName));
                else
                    tables[tableKey] = entity.EntityName;

                var source = EfMappingEmitter.Emit(
                    rootNamespace,
                    entity,
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

                context.AddSource($"{entity.EntityName}Map.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        context.AddSource("GeneratedDataProvider.g.cs", SourceText.From($$"""
            // <auto-generated/>
            namespace {{rootNamespace}};

            /// <summary>The provider these mappings were generated for.</summary>
            public static class GeneratedDataProvider
            {
                public const string Name = "{{providerName}}";
            }
            """, Encoding.UTF8));
    }

    private static bool Validate(SourceProductionContext context, EntitySchema entity, INamedTypeSymbol symbol)
    {
        var ok = true;

        foreach (var column in entity.Columns)
            if (!HasProperty(symbol, column.Property))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MappingDiagnostics.PropertyNotFound, Location.None,
                    entity.EntityName, column.Property, column.Column));

                ok = false;
            }

        if (!HasProperty(symbol, entity.Key))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MappingDiagnostics.PropertyNotFound, Location.None,
                entity.EntityName, entity.Key, entity.Key));

            ok = false;
        }

        return ok;
    }

    private static bool HasProperty(INamedTypeSymbol type, string name)
    {
        for (var current = type; current is not null; current = current.BaseType)
            if (current.GetMembers(name).Any(m => m.Kind == SymbolKind.Property))
                return true;

        return type.AllInterfaces.Any(i => i.GetMembers(name).Any(m => m.Kind == SymbolKind.Property));
    }

    private static INamedTypeSymbol? FindEntity(Compilation compilation, string name)
    {
        INamedTypeSymbol? found = null;

        void Walk(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
                if (found is null && type.Name == name)
                    found = type;

            foreach (var child in ns.GetNamespaceMembers())
                if (found is null) Walk(child);
        }

        Walk(compilation.Assembly.GlobalNamespace);

        // Entity'ler genelde ayri bir Data.Domain projesinde; referanslara da bak.
        if (found is null)
            foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                // Framework assemblies cannot contain project entities.
                if (assembly.Name.StartsWith("System", StringComparison.Ordinal)
                 || assembly.Name.StartsWith("Microsoft", StringComparison.Ordinal)
                 || assembly.Name.StartsWith("netstandard", StringComparison.Ordinal)) continue;

                Walk(assembly.GlobalNamespace);

                if (found is not null) break;
            }

        return found;
    }

    private static EntitySchema? Read(string entityName, JsonValue value)
    {
        if (!value.IsObject) return null;

        var table = value.GetString("Table");

        if (table is null) return null;

        var columns = ImmutableArray.CreateBuilder<ColumnSchema>();
        var columnsNode = value.Get("Columns");

        if (columnsNode is { IsObject: true })
            foreach (var pair in columnsNode.Object)
            {
                var column = pair.Value.GetString("Column");

                if (column is null) continue;

                columns.Add(new ColumnSchema(
                    pair.Key,
                    column,
                    pair.Value.GetInt("MaxLength"),
                    pair.Value.GetBool("Required"),
                    pair.Value.GetString("ColumnType")));
            }

        return new EntitySchema(
            entityName,
            table,
            value.GetString("Schema"),
            value.GetString("Key") ?? "Id",
            value.GetBool("Legacy"),
            new EquatableArray<ColumnSchema>(columns.ToImmutable()));
    }

    private static string Path(string path)
    {
        var index = path.LastIndexOfAny(['/', '\\']);
        return index < 0 ? path : path.Substring(index + 1);
    }

    private sealed record SchemaFile(string Path, string Content);
}
