using System.Text;
using IQOne.Zero.Tool.Capabilities;

namespace IQOne.Zero.Tool.Rules;

/// <summary>
/// Writes what an agent needs to work inside Zero: the catalog of what exists, and the
/// rules for using it.
/// </summary>
/// <remarks>
/// Everything goes inside a marked block that is rewritten in place, so re-running after an
/// upgrade never destroys what a person wrote around it.
/// </remarks>
internal static class RuleWriter
{
    private const string Begin = "<!-- BEGIN IQOne.Zero -->";
    private const string End = "<!-- END IQOne.Zero -->";

    // Matched by prefix so a block written by an older version is replaced rather than
    // duplicated. Renaming a marker must never leave two blocks behind.
    private const string BeginPrefix = "<!-- BEGIN IQOne.Zero";
    private const string EndPrefix = "<!-- END IQOne.Zero";

    public static IReadOnlyList<string> Write(
        string directory,
        IReadOnlyList<Capability> capabilities,
        Catalog? catalog,
        IReadOnlyList<RuleFile> rules)
    {
        var written = new List<string>();

        var agents = Path.Combine(directory, "AGENTS.md");
        WriteBlock(agents, Compose(capabilities, catalog, rules));
        written.Add(agents);

        // Claude Code reads CLAUDE.md; an import keeps one source of truth.
        var claude = Path.Combine(directory, "CLAUDE.md");
        WriteBlock(claude, "@AGENTS.md\n");
        written.Add(claude);

        var cursor = Path.Combine(directory, ".cursor", "rules");
        Directory.CreateDirectory(cursor);

        // Clear what a previous run wrote, so a rule removed upstream stops being applied.
        foreach (var stale in Directory.EnumerateFiles(cursor, "zero-*.mdc")) File.Delete(stale);

        foreach (var rule in rules)
        {
            var path = Path.Combine(cursor, $"zero-{rule.Slug}.mdc");
            File.WriteAllText(path, CursorRule(rule));
            written.Add(path);
        }

        return written;
    }

    private static string Compose(
        IReadOnlyList<Capability> capabilities, Catalog? catalog, IReadOnlyList<RuleFile> rules)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# Zero");
        builder.AppendLine();

        if (catalog is { Purpose.Length: > 0 })
            builder.AppendLine(catalog.Purpose).AppendLine();

        builder.AppendLine("This file is generated by `zero rules init` from the Zero packages this project");
        builder.AppendLine("references. Do not edit inside the marked block; anything outside it is kept.");
        builder.AppendLine();

        if (catalog is { ReadThisFirst.Length: > 0 })
        {
            builder.AppendLine("## Before you write a foundational abstraction");
            builder.AppendLine();
            builder.AppendLine(catalog.ReadThisFirst);
            builder.AppendLine();
        }

        AppendInstalled(builder, capabilities);
        AppendAvailable(builder, capabilities, catalog);
        AppendRules(builder, rules);

        return builder.ToString();
    }

    private static void AppendInstalled(StringBuilder builder, IReadOnlyList<Capability> capabilities)
    {
        if (capabilities.Count == 0) return;

        builder.AppendLine("## What this project already has");
        builder.AppendLine();
        builder.AppendLine("| Capability | Use it for | Turn it on with |");
        builder.AppendLine("| --- | --- | --- |");

        foreach (var capability in capabilities)
        {
            var entry = capability.EntryPoint is null ? "—" : $"`{capability.EntryPoint}`";
            builder.AppendLine($"| {capability.Title} | {capability.UseWhen} | {entry} |");
        }

        builder.AppendLine();

        foreach (var capability in capabilities)
        {
            builder.Append("### ").AppendLine(capability.Title);
            builder.AppendLine();
            builder.AppendLine(capability.Summary);
            builder.AppendLine();
            var facts = new List<string> { $"Package `{capability.Package}` {capability.Version}" };

            if (capability.KeyTypes.Count > 0)
                facts.Add($"Types you touch: {string.Join(", ", capability.KeyTypes.Select(t => $"`{t}`"))}");

            if (capability.Diagnostics.Count > 0)
                facts.Add($"Enforced by {string.Join(", ", capability.Diagnostics)}");

            builder.AppendLine(string.Join(". ", facts) + ".");

            if (capability.Example is { Length: > 0 })
            {
                builder.AppendLine();
                builder.AppendLine("```csharp");
                builder.AppendLine(capability.Example.TrimEnd());
                builder.AppendLine("```");
            }

            builder.AppendLine();
        }
    }

    private static void AppendAvailable(
        StringBuilder builder, IReadOnlyList<Capability> installed, Catalog? catalog)
    {
        if (catalog is null) return;

        var have = installed.Select(c => c.Package).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var missing = catalog.Capabilities.Where(c => !have.Contains(c.Package)).ToList();

        if (missing.Count == 0) return;

        builder.AppendLine("## What Zero also offers, not installed here");
        builder.AppendLine();
        builder.AppendLine("Reach for one of these before writing your own. Add it with");
        builder.AppendLine("`dotnet add package <package>`, then make its single `Add` call — and say so, rather");
        builder.AppendLine("than adding a dependency silently.");
        builder.AppendLine();
        builder.AppendLine("| Package | Use it for |");
        builder.AppendLine("| --- | --- |");

        foreach (var capability in missing)
            builder.AppendLine($"| `{capability.Package}` | {capability.UseWhen} |");

        builder.AppendLine();
    }

    private static void AppendRules(StringBuilder builder, IReadOnlyList<RuleFile> rules)
    {
        if (rules.Count == 0) return;

        builder.AppendLine("## Rules");
        builder.AppendLine();
        builder.AppendLine("These are not style preferences. Most are enforced by analyzers, so breaking one");
        builder.AppendLine("fails the build.");

        foreach (var rule in rules)
        {
            builder.AppendLine();
            builder.AppendLine("---");
            builder.AppendLine();
            builder.Append("### ").AppendLine(rule.Title);
            builder.AppendLine();

            if (rule.EnforcedBy.Count > 0)
                builder.AppendLine($"*Enforced by {string.Join(", ", rule.EnforcedBy)}.*").AppendLine();

            builder.AppendLine(Demote(rule.Body));
        }
    }

    /// <summary>
    /// Pushes a rule's own headings below the heading it is nested under, so the composed
    /// file has one coherent outline instead of a rule's "## Do" competing with "## Rules".
    /// </summary>
    private static string Demote(string body)
    {
        var lines = body.Split('\n');
        var inFence = false;

        for (var i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("```", StringComparison.Ordinal)) inFence = !inFence;
            else if (!inFence && lines[i].StartsWith("#", StringComparison.Ordinal)) lines[i] = "#" + lines[i];
        }

        return string.Join('\n', lines);
    }

    private static string CursorRule(RuleFile rule) =>
        $"""
         ---
         description: {rule.Title}
         alwaysApply: true
         ---

         {rule.Body}
         """;

    /// <summary>Replaces the managed block, or appends one, leaving everything else intact.</summary>
    private static void WriteBlock(string path, string content)
    {
        var block = $"{Begin}\n{content.TrimEnd()}\n{End}\n";

        if (!File.Exists(path))
        {
            File.WriteAllText(path, block);
            return;
        }

        var existing = File.ReadAllText(path);
        var start = existing.IndexOf(BeginPrefix, StringComparison.Ordinal);
        // Last, not first: a file left with two blocks by an older version collapses to one.
        var finish = existing.LastIndexOf(EndPrefix, StringComparison.Ordinal);

        if (start >= 0 && finish > start)
        {
            var afterEnd = existing.IndexOf("-->", finish, StringComparison.Ordinal);
            var tail = afterEnd < 0 ? string.Empty : existing[(afterEnd + 3)..].TrimStart('\n');

            File.WriteAllText(path, existing[..start] + block + tail);
            return;
        }

        File.WriteAllText(path, existing.TrimEnd() + "\n\n" + block);
    }
}
